"""create initial tables

Revision ID: 0968d871b825
Revises: 
Create Date: 2025-09-19 04:43:31.729192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0968d871b825'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('domain_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('current_status', sa.Enum('OPEN', 'UNDER_REVIEW', 'REVIEWED', 'ESCALATED', 'SUSPENDED', 'CLOSED', name='domainstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('domain_id')
    )
    op.create_index(op.f('ix_domains_domain_name'), 'domains', ['domain_name'], unique=True)
    op.create_table('domain_status_history',
    sa.Column('status_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('new_status', sa.Enum('OPEN', 'UNDER_REVIEW', 'REVIEWED', 'ESCALATED', 'SUSPENDED', 'CLOSED', name='domainstatus'), nullable=False),
    sa.Column('reviewer_initials', sa.String(length=8), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.domain_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('status_id')
    )
    op.create_index(op.f('ix_domain_status_history_domain_id'), 'domain_status_history', ['domain_id'], unique=False)
    op.create_table('reports',
    sa.Column('report_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('reporter_source', sa.String(length=100), nullable=False),
    sa.Column('abuse_type', sa.Enum('PHISHING', 'MALWARE', 'BOTNET_C2', 'CSAM', 'SPAM', 'OTHER', name='abusetype'), nullable=False),
    sa.Column('reported_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence_score', sa.SmallInteger(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevel'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.domain_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index(op.f('ix_reports_domain_id'), 'reports', ['domain_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_domain_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_domain_status_history_domain_id'), table_name='domain_status_history')
    op.drop_table('domain_status_history')
    op.drop_index(op.f('ix_domains_domain_name'), table_name='domains')
    op.drop_table('domains')
    # ### end Alembic commands ###
